version: 2
updates:
# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100